import Head from 'next/head';

import Navbar from '../src/components/Navbar';
import Intro from '../src/sections/HomeIntro';
import Skills from '../src/sections/Skills';
import Education from '../src/sections/Education';
import Experience from '../src/sections/Experience';

export default function Home() {
  return (
    <>
      <Head>
        <title>Rashid's Portfolio</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <Navbar />
      <main>
        <section id="home" className="pt-24 min-h-screen">
          <Intro />
        </section>
        <section id="portfolio" className="mx-auto pt-16">
          <Skills />
        </section>
        <section className="mb-24">
          <Education />
        </section>
        <section className="mb-24">
          <Experience />
        </section>
      </main>
      <footer></footer>
    </>
  );
}
