import Head from "next/head";
import Navbar from "../src/components/Navbar";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* <main className="h-screen w-screen flex justify-center items-center"> */}
      {/* <ThemeToggler /> */}

      {/* <Signature className="w-44 fill-slate-800" /> */}
      {/* </main> */}
      <Navbar />

      <footer></footer>
    </div>
  );
}
